baseURL = 'https://www.kiwigpt.co.nz/'
languageCode = 'en-us'
title = 'KiwiGPT'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Daily Briefs"
    url = "/briefs/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Series"
    url = "/series/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[params]
  title = 'KiwiGPT'
  description = 'AI research insights and thought leadership'
  author = 'KiwiGPT'

  [params.label]
    icon = "/KiwiGPT_ico.png"
    iconHeight = 50

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
