baseURL = 'https://www.kiwigpt.co.nz/'
languageCode = 'en-us'
title = 'Kiwigpt'
theme = 'PaperMod'

[params]
  title = 'Kiwigpt'
  description = 'AI research insights and thought leadership'
  author = 'Kiwigpt'
