baseURL = 'https://www.kiwigpt.co.nz/'
languageCode = 'en-us'
title = 'KiwiGPT'
theme = 'PaperMod'
enableRobotsTXT = true

[services]
  [services.googleAnalytics]
    ID = "G-Q2XVVBQ36H"
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
   [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
   [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[params]
  title = 'KiwiGPT'
  description = "A Kiwi Generating, Publishing, and Tinkering with AI — ideas in public and small products (some polished, some gloriously half-built)."
  author_name = "Saurabh Dhawan"
  mainSections = ["posts"]
  
  [params.profileMode]
    enabled = false
  
  [params.label]
    icon = "/KiwiGPT_ico.png"
    iconHeight = 50

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"

  # Optional analytics settings (Search Console, etc.)
  [params.analytics]
    [params.analytics.google]
      SiteVerificationTag = ""

[markup.goldmark.renderer]
unsafe = true
